# Indentation is important!
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  # "name" is globally unique. It is not cross-referenced
  # anywhere, so it can be changed freely without side effects.
  # It is the name that appears in "wash app list".
  # It is the name used in "wash call", like so:
  # wash call sqlite_invoker_app-invoker example:invoker/invoker.call
  name: sqlite-invoker-app 
  annotations:
    description: Prelim SQLte connectivity demo
    wasmcloud.dev/categories: go,example
    version: 0.0.1 # (optional, but autogen is orgly) 
spec:
  components:
    - name: invoker
      type: component
      properties:
      # image may point to a local .wasm binary,
      # or an OCI artifact in an OCI registry
        image: file://./build/invoke_s.wasm
      # id: (optional; if none is provided, wadm assigns
      # a generated identifier, which is a combo of the
      # manifest name and the component name.)
      # config: (optional; generally most useful for
      # making arbitrary data available at runtime
      # via the wasi-runtime-config interface.)
      traits:
      # Traits are metadata associated with a component.
      # Supported: spreadscaler, daemonscaler, link.
        - type: spreadscaler
          properties:
            replicas: 1
